.TH "/Users/fredericosilva/Documents/IPCA/Ano1/Semestre2/EDA/TP Directory Reference" 3 "Fri Apr 1 2022" "Version 1.0" "EDA-TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/fredericosilva/Documents/IPCA/Ano1/Semestre2/EDA/TP Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdataStructures\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "Ficheiro principal da aplicação, com os testes e as funções da aplicação\&. "
.ti -1c
.RI "file \fBmanager\&.c\fP"
.br
.RI "Ficheiro com so funções à gestão de linked list: Jobs, Operations, \fBOperationMachine\fP\&. "
.ti -1c
.RI "file \fBmanager\&.h\fP"
.br
.ti -1c
.RI "file \fBpersistance\&.c\fP"
.br
.ti -1c
.RI "file \fBpersistance\&.h\fP"
.br
.in -1c
