.TH "/Users/fredericosilva/Documents/IPCA/Ano1/Semestre2/EDA/TP/dataStructures.h" 3 "Fri Apr 1 2022" "Version 1.0" "EDA-TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/fredericosilva/Documents/IPCA/Ano1/Semestre2/EDA/TP/dataStructures.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBOperationMachine\fP"
.br
.RI "Estrutura de uma operação-máquina\&. "
.ti -1c
.RI "struct \fBOperationMachineNode\fP"
.br
.RI "Nó de uma operação-máquina na linked list\&. "
.ti -1c
.RI "struct \fBOperation\fP"
.br
.RI "Estrutura de uma operação\&. "
.ti -1c
.RI "struct \fBOperationNode\fP"
.br
.RI "Nó de uma operação na linked list\&. "
.ti -1c
.RI "struct \fBMachine\fP"
.br
.RI "Máquina\&. "
.ti -1c
.RI "struct \fBJob\fP"
.br
.RI "Estrutura de um job\&. "
.ti -1c
.RI "struct \fBJobNode\fP"
.br
.RI "Nó de um job na linked list\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDADOSGLOBAIS\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBOperationMachine\fP \fBOperationMachine\fP"
.br
.RI "Estrutura de uma operação-máquina\&. "
.ti -1c
.RI "typedef struct \fBOperationMachineNode\fP \fBOperationMachineNode\fP"
.br
.RI "Nó de uma operação-máquina na linked list\&. "
.ti -1c
.RI "typedef struct \fBOperation\fP \fBOperation\fP"
.br
.RI "Estrutura de uma operação\&. "
.ti -1c
.RI "typedef struct \fBOperationNode\fP \fBOperationNode\fP"
.br
.RI "Nó de uma operação na linked list\&. "
.ti -1c
.RI "typedef struct \fBMachine\fP \fBMachine\fP"
.br
.RI "Máquina\&. "
.ti -1c
.RI "typedef struct \fBJob\fP \fBJob\fP"
.br
.RI "Estrutura de um job\&. "
.ti -1c
.RI "typedef struct \fBJobNode\fP \fBJobNode\fP"
.br
.RI "Nó de um job na linked list\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DADOSGLOBAIS   1"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBJob\fP \fBJob\fP"

.PP
Estrutura de um job\&. 
.SS "typedef struct \fBJobNode\fP \fBJobNode\fP"

.PP
Nó de um job na linked list\&. 
.SS "typedef struct \fBMachine\fP \fBMachine\fP"

.PP
Máquina\&. 
.SS "typedef struct \fBOperation\fP \fBOperation\fP"

.PP
Estrutura de uma operação\&. 
.SS "typedef struct \fBOperationMachine\fP \fBOperationMachine\fP"

.PP
Estrutura de uma operação-máquina\&. 
.SS "typedef struct \fBOperationMachineNode\fP \fBOperationMachineNode\fP"

.PP
Nó de uma operação-máquina na linked list\&. 
.SS "typedef struct \fBOperationNode\fP \fBOperationNode\fP"

.PP
Nó de uma operação na linked list\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-TP1 from the source code\&.
