.TH "Job" 3 "Mon Mar 28 2022" "Eda-tp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Job
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBOperationNode\fP * \fBoperations\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Eda-tp from the source code\&.
