.TH "JobFile" 3 "Tue May 31 2022" "EDA-FJSSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JobFile \- Estrutura de um job em ficheiro\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <persistance\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de um job em ficheiro\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-FJSSP from the source code\&.
