.TH "JobNode" 3 "Tue May 31 2022" "EDA-FJSSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JobNode \- Nó de um job na linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataStructures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBJob\fP \fBjob\fP"
.br
.ti -1c
.RI "struct \fBJobNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nó de um job na linked list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-FJSSP from the source code\&.
