.TH "JobNode" 3 "Fri Apr 1 2022" "Version 1.0" "EDA-TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JobNode \- Nó de um job na linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataStructures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBJob\fP \fBjob\fP"
.br
.ti -1c
.RI "struct \fBJobNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nó de um job na linked list\&. 
.SH "Field Documentation"
.PP 
.SS "\fBJob\fP job"

.SS "struct \fBJobNode\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-TP1 from the source code\&.
