.TH "Machine" 3 "Fri Apr 1 2022" "Version 1.0" "EDA-TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Machine \- Máquina\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataStructures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBisBusy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Máquina\&. 
.SH "Field Documentation"
.PP 
.SS "int id"

.SS "int isBusy"


.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-TP1 from the source code\&.
