.TH "/Users/fredericosilva/Documents/IPCA/Ano1/Semestre2/EDA/TP/main.c" 3 "Fri Apr 1 2022" "Version 1.0" "EDA-TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/fredericosilva/Documents/IPCA/Ano1/Semestre2/EDA/TP/main.c \- Ficheiro principal da aplicação, com os testes e as funções da aplicação\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'dataStructures\&.h'\fP
.br
\fC#include 'persistance\&.h'\fP
.br
\fC#include 'manager\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBJOBS_FILE\fP   'Resources/jobs\&.bin'"
.br
.ti -1c
.RI "#define \fBOPERATIONS_FILE\fP   'Resources/operations\&.bin'"
.br
.ti -1c
.RI "#define \fBOPERATION_MACHINES_FILE\fP   'Resources/operation_machines\&.bin'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Ficheiro principal da aplicação, com os testes e as funções da aplicação\&. 


.PP
\fBAuthor\fP
.RS 4
Pedro Silva @email a20721@alunos.ipca.pt 
.RE
.PP
\fBDate\fP
.RS 4
31/03/2022 
.RE
.PP
\fBSee also\fP
.RS 4
https://github.com/FredSilva92/EDA-TP1.git 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define JOBS_FILE   'Resources/jobs\&.bin'"

.SS "#define OPERATION_MACHINES_FILE   'Resources/operation_machines\&.bin'"

.SS "#define OPERATIONS_FILE   'Resources/operations\&.bin'"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-TP1 from the source code\&.
