.TH "OperationMachineNode" 3 "Tue May 31 2022" "EDA-FJSSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationMachineNode \- Nó de uma operação-máquina na linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataStructures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOperationMachine\fP \fBoperationMachine\fP"
.br
.ti -1c
.RI "struct \fBOperationMachineNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nó de uma operação-máquina na linked list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-FJSSP from the source code\&.
