.TH "OperationMachine" 3 "Tue May 31 2022" "EDA-FJSSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationMachine \- Estrutura de uma operação-máquina\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataStructures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmachineId\fP"
.br
.ti -1c
.RI "int \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de uma operação-máquina\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-FJSSP from the source code\&.
