.TH "OperationMachineFile" 3 "Mon Mar 28 2022" "Eda-tp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationMachineFile
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBjobId\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBtime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Eda-tp from the source code\&.
