.TH "OperationNode" 3 "Tue May 31 2022" "EDA-FJSSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationNode \- Nó de uma operação na linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataStructures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOperation\fP \fBoperation\fP"
.br
.ti -1c
.RI "struct \fBOperationNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nó de uma operação na linked list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-FJSSP from the source code\&.
