.TH "OperationNode" 3 "Fri Apr 1 2022" "Version 1.0" "EDA-TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationNode \- Nó de uma operação na linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataStructures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBOperation\fP \fBoperation\fP"
.br
.ti -1c
.RI "struct \fBOperationNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nó de uma operação na linked list\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBOperationNode\fP* next"

.SS "\fBOperation\fP operation"


.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-TP1 from the source code\&.
