.TH "OperationMachineNode" 3 "Fri Apr 1 2022" "Version 1.0" "EDA-TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationMachineNode \- Nó de uma operação-máquina na linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataStructures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBOperationMachine\fP \fBoperationMachine\fP"
.br
.ti -1c
.RI "struct \fBOperationMachineNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nó de uma operação-máquina na linked list\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBOperationMachineNode\fP* next"

.SS "\fBOperationMachine\fP operationMachine"


.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-TP1 from the source code\&.
