.TH "OperationNode" 3 "Mon Mar 28 2022" "Eda-tp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationNode
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBOperation\fP \fBoperation\fP"
.br
.ti -1c
.RI "struct \fBOperationNode\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Eda-tp from the source code\&.
