.TH "OperationMachine" 3 "Fri Apr 1 2022" "Version 1.0" "EDA-TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationMachine \- Estrutura de uma operação-máquina\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dataStructures\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmachineId\fP"
.br
.ti -1c
.RI "int \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de uma operação-máquina\&. 
.SH "Field Documentation"
.PP 
.SS "int machineId"

.SS "int time"


.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-TP1 from the source code\&.
