.TH "OperationMachineFile" 3 "Tue May 31 2022" "EDA-FJSSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationMachineFile \- Estrutura de uma operação-máquina em ficheiro\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <persistance\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBjobId\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de uma operação-máquina em ficheiro\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-FJSSP from the source code\&.
