.TH "OperationFile" 3 "Fri Apr 1 2022" "Version 1.0" "EDA-TP1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationFile \- Estrutura de uma operação em ficheiro\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <persistance\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de uma operação em ficheiro\&. 
.SH "Field Documentation"
.PP 
.SS "int id"

.SS "char* name"


.SH "Author"
.PP 
Generated automatically by Doxygen for EDA-TP1 from the source code\&.
